app/models/user.py
from flask import session
from app.database.db_connection import Database
from app.utils.security_utils import hash_password, check_password

class User:
    def __init__(self, id: int = None, name: str = None, lastname: str = None, email: str = None, password: str = None):
        self.id = id
        self.name = name
        self.lastname = lastname
        self.email = email
        self.password = password
    
    def login(self):
        """Logea al usuario usando los atributos de la instancia."""
        query = "SELECT id, password FROM users WHERE email = %s"
        values = (self.email,)
        
        with Database() as db:
                db.execute(query, values)
                user_result = db.fetchone()
                if user_result and check_password(user_result['password'], self.password):
                    session["user_id"] = user_result["id"]
                    return True
                else:
                    return False

    def register(self):
        """Registra al usuario usando los atributos de la instancia."""
        try:
            hashed_password = hash_password(self.password)
            query = "INSERT INTO users (name, lastname, email, password, register_date) VALUES (%s, %s, %s, %s, NOW())"
            values = (self.name, self.lastname, self.email, hashed_password)

            with Database() as db:
                db.execute(query, values)
                db.commit()

            return {"success": True, "message": "Usuario registrado exitosamente."}
        
        except Exception as e:
            return {"success": False, "error": f"Error inesperado: {e}"}
        
    def get_login_data(self):
        """Obtiene los datos del usuario logueado."""
        query = "SELECT name FROM users WHERE id = %s"
        values = (self.id,)
        
        with Database() as db:
            db.execute(query, values)
            login_data = db.fetchone()
            return login_data

app/__init__.py
from flask import Flask, session
from flask_session import Session
from config.config import flask_config
from app.database.db_dll import DLL

def create_app():
    app = Flask(__name__)
    app.secret_key = flask_config['SECRET_KEY']
    app.config.update(flask_config)

    # Inicializar Flask-Session
    Session(app)

    # Crear la base de datos y tablas si no existen
    DLL()

    @app.before_request
    def make_session_permanent():
        session.permanent = True

    # Importar y registrar Blueprints
    from app.routes.main import main
    from app.routes.auth_routes import auth_routes
    app.register_blueprint(main)
    app.register_blueprint(auth_routes)


    return app

app/routes/auth_routes.py
from flask import request, session, redirect, render_template
from flask import Blueprint, render_template
from flask import jsonify
from app.models.user import User
from app.services.user_service import UserService

# Blueprint llamado 'main'
auth_routes = Blueprint('auth_routes', __name__)

@auth_routes.route('/ingresar')
def login():
    return render_template('auth/login.html')

@auth_routes.route('/registrar')
def register():
    return render_template('auth/register.html')

@auth_routes.route("/login_user", methods=["POST"])
def login_user():
    if request.method == "POST":
        # Obtener los datos del formulario
        email = request.form["email"]
        password = request.form["password"]

        # Validar los datos del formulario
        user_service = UserService(email=email)
        user_service.validate_email()

        # Logear al usuario
        if User(email=email, password=password).login():
            # Si el login es exitoso
            return jsonify({"success": True, "message": "Inicio de sesión exitoso."})
        else:
            # Si el login falla
            return jsonify({"success": False, "message": "Contraseña o email incorrectos."})

@auth_routes.route("/register_user", methods=["POST"])
def register_user():
    if request.method == "POST":
        # Obtener los datos del formulario
        name = request.form["name"]
        lastname = request.form["lastname"]
        email = request.form["email"]
        password = request.form["password"]
        password_confirm = request.form["password_confirm"]

        # Validar los datos del formulario
        user_service = UserService(name=name, 
                                   lastname=lastname, 
                                   email=email, 
                                   password=password, 
                                   password_confirm=password_confirm)
        user_service.validate_all()

        # Registrar al usuario
        User(name=name, lastname=lastname, email=email, password=password).register()
        
        return redirect("/ingresar")  # Redirige al login después de registrar
    
    return render_template("register.html")  # Muestra el formulario si es GET

@auth_routes.route("/logout", methods=["POST"])
def logout():
    """Cierra la sesión del usuario."""
    session.pop("user_id", None)
    return redirect("/ingresar")

app/routes/main.py
from flask import Blueprint, session, redirect, render_template, request
from app.models.user import User

# Blueprint llamado 'main'
main = Blueprint('main', __name__)

@main.route('/')
def index():

    # Verificar si el usuario está logueado y obtener sus datos de sesión
    user_id = session.get("user_id")
    user_login_data = User(id=user_id).get_login_data()
    if not user_login_data:
        return render_template("index.html")

    return render_template('index.html', user_login_data=user_login_data)

app/templates/base.html
<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    
    <!-- Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- Bootstrap Icons -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css" rel="stylesheet">
    <!-- CSS globales-->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/info-card.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/forms.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/buttons.css') }}">
    <!-- CSS por página -->
    {% block css %}{% endblock %}

</head>

<body>
    <!-- Header de la página -->
     {% block header %}
    <header>
        <!-- Navbar -->
        <nav class="navbar navbar-expand-sm fixed-top">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">Fixed top</a>
                <div style="display: flex; flex-direction: row; align-items: center; justify-content: center;">
                    {% if session.get('user_id') %}
                        <div style="display: flex; align-items: center; gap: 10px;">
                            <h5 style="margin: 0;">¡Hola!, {{ user_login_data['name'] }}</h5>
                            <form action="/logout" method="POST">
                                <button type="submit" style="width: 150px; padding: 5px; background-color: #f44336; color: white; border: none; cursor: pointer; border-radius: 5px;">
                                    Cerrar sesión
                                </button>
                            </form>
                        </div>
                    {% else %}
                        <a href="{{ url_for('auth_routes.login') }}" style="text-decoration: none; color: #007bff;">Ingresar</a>
                    {% endif %}

                </div>
            </div>
        </nav>
    </header>
    {% endblock %}

    <!-- Contenido principal -->
    <main>
        {% block content %}{% endblock %}
    </main>

    <!-- Footer de la página -->
    <footer>

    </footer>
    <!-- Bootstrap -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- SweetAlert -->
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <!-- JavaScript globales -->
    <script src="{{ url_for('static', filename='js/utils.js') }}"></script>
    <!-- JavaScript por página -->
    {% block js %}{% endblock %}
</body>

</html>

app/templates/error.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Error</h1> 
</body>
</html>

app/templates/index.html
{% extends 'base.html' %}
{% block title %}Inicio{% endblock %}

<!-- Estilos css personalizados por página -->
{% block css %}
{% endblock %}

<!-- Contenido principal de la página -->
{% block content %}
<div class="container-fluid cont-main">
    <div class="row gx-0">
        <div class="col cont-top-buttons">
            <!-- Button to Open the Modal -->
            <a class="btn btn-category" href="">Boton secundary</a>
            </button>
            <!-- Button to Open the Modal -->
            <button type="button" class="btn btn-blue" data-bs-toggle="modal" data-bs-target="#crearFamilia">
                Boton primary
            </button>
        </div>
    </div>
</div>

<!-- Modal para registrar egreso -->
<div class="modal fade" id="crearFamilia">
    <div class="modal-dialog">
        <div class="modal-content">
            <form id="egresoForm" action="/create_family" method="POST">
                <!-- Modal Header -->
                <div class="modal-header">
                    <h4 class="modal-title">Crear grupo familiar</h4>
                    <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
                </div>

                <!-- Modal Body -->
                <div class="modal-body">

                    <div class="cont-label-input">
                        <label for="monto">Nombre de la familia</label>
                        <input type="text" id="family_name" name="family_name" required>
                        <span class="error" id="montoError"></span>
                    </div>

                </div>

                <!-- Modal Footer -->
                <div class="modal-footer">
                    <button type="submit" class="btn btn-blue">Crear</button>
                </div>
            </form>

            <style>
                .error {
                    color: red;
                    font-size: 0.875em;
                    display: block;
                    margin-top: 5px;
                }
            </style>

        </div>
    </div>
</div>
{% endblock %}

<!-- JavaScript personalizado por página -->
{% block js %}
<script src="{{ url_for('static', filename='js/swal-login-response.js') }}"></script>
{% endblock %}